### ISSUE TITLE
Revisão e submissão do Projeto Salus à Plataforma Brasil

### ISSUE THREAD

**Issue by leojasmim** [LPPUnifeso/Salus#1]
- [x] @LPPUnifeso/saluscoordenacao @LPPUnifeso/salusmedicina : Revisar o anteprojeto Salus;

- [x] @leojasmim: Rever os anexos;

- [x] @jrobert-andrade : Após a #6 e submeter o Projeto ao CEP através da Plataforma Brasil.

**Comment by leojasmim** [comment]
@LPPUnifeso/salusccomp @LPPUnifeso/salusmedicina 
Aguardando revisar projeto para submissão.

**Comment by leojasmim** [comment]
@jrobert-andrade Documento revisado na pasta de <Documentos> do OneDrive. Falta inserir os dados do Vitor para finalizar.

**Comment by jrobert-andrade** [comment]
@leojasmim Inseri os dados na Plataforma, mas estou com problemas para assinalar a Instituição. Vou checar amanhã com a DPPE e submeter.

**Comment by jrobert-andrade** [comment]
projeto submetido à Plataforma Brasil
