### ISSUE TITLE
Estudar ARIS Express  e BPMN

### ISSUE THREAD

**Issue by leojasmim** [LPPUnifeso/Salus#14]
- [x] @leojasmim: Pesquisar sobre BPMN (Business Process Model and Notation) e o Aris Express.

- [ ] @jrobert-andrade : Pesquisar sobre BPMN (Business Process Model and Notation) e o Aris Express.

- [ ] @vitordsribeiro : Pesquisar sobre BPMN (Business Process Model and Notation) e o Aris Express.

- [x] @pedrohmo : Pesquisar sobre BPMN (Business Process Model and Notation) e o Aris Express.

- [x] @mayarabueno : Pesquisar sobre BPMN (Business Process Model and Notation) e o Aris Express.

Links para iniciar estudo: http://www.bpmn.org/  e http://www.ariscommunity.com/aris-express

**Comment by leojasmim** [comment]
@LPPUnifeso/salusccomp @LPPUnifeso/salusmedicina : Em minha pesquisa encontrei essa playlist sobre uma outra ferramenta, o Bizagi. Achei interessante a ferramenta por ser mais intuitiva para quem não está muito habituado... De qualquer forma acho que a playlist é interessante sobre a utilização da notação BPMN, independente da ferramenta... 
Playlist: [https://www.youtube.com/playlist?list=PLGzr5PC9lQ38GAIv2-iBPdeY38JPHRoIy](url)

**Comment by mayarabueno** [comment]
pesquisa concluída

**Comment by pedrohmo** [comment]
pesquisa finalizada
