### ISSUE TITLE
Apresentação sobre a reunião "Zika na Gestante"

### ISSUE THREAD

**Issue by leojasmim** [LPPUnifeso/Salus#16]
- [x] @mayarabueno : Preparar apresentação (oral apenas) sobre as impressões da reunião no próximo dia 19/05/2016 (quinta-feira) às 14h, na Sociedade Médica de Teresópolis, sito à Rua Wilhelm Cristian Klene, 680, Ermitage ( ao lado da APAE).

- [x] @pedrohmo : Preparar apresentação (oral apenas) sobre as impressões da reunião no próximo dia 19/05/2016 (quinta-feira) às 14h, na Sociedade Médica de Teresópolis, sito à Rua Wilhelm Cristian Klene, 680, Ermitage ( ao lado da APAE).

**Comment by mayarabueno** [comment]
apresentação oral preparada

**Comment by pedrohmo** [comment]
apresentação oral pronta

**Comment by pedrohmo** [comment]
#16 finalizado
