### ISSUE TITLE
Solicitação de acesso à Secretaria de Saúde

### ISSUE THREAD

**Issue by leojasmim** [LPPUnifeso/Salus#2]
- [x] @jrobert-andrade : Após #1, preparar ofício à Secretaria de Saúde com cópia do projeto solicitando autorização para acesso aos dados e unidades.

- [x] @leojasmim : Encaminhar ofício.

**Comment by leojasmim** [comment]
Modelo do ofício anexado ao OneDrive. 
@jrobert-andrade anexar versão final do projeto em .docx (VFinal)

**Comment by jrobert-andrade** [comment]
Ofício e arquivo do Projeto encaminhado ao CEP em Word anexados ao One Drive

**Comment by jrobert-andrade** [comment]
A nova versão, alterada pela Edenise, foi anexada ao One Drive. Após o encaminhamento e assinatura do Secretário anexaremos a versão final.

**Comment by jrobert-andrade** [comment]
Ofício encaminhado
